### ISSUE TITLE
multi-thread REST call not work

### ISSUE THREAD

**Issue by laoshanxi** [libcpr/cpr#833]
I am trying to use multi-thread REST call and some REST are used for call Consul Block Query API which will block some seconds in REST server side, and with this, I found other cpr REST can not send out. seems multi-thread is not supported

```
Thread 7 (Thread 0x7fcdf907d700 (LWP 216816)):
#0  0x00007fcdfe4f699f in __GI___poll (fds=0x7fcdf907a8e0, nfds=2, timeout=1000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcdfe29de75 in Curl_poll (ufds=0x7fcdf907a8e0, nfds=2, timeout_ms=1000) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/select.c:374
#2  0x00007fcdfe29580f in multi_wait (multi=0x7fcde400fce0, extra_fds=0x0, extra_nfds=0, timeout_ms=1000, ret=0x0, extrawait=true, use_wakeup=true) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1282
#3  0x00007fcdfe295b18 in curl_multi_poll (multi=0x7fcde400fce0, extra_fds=0x0, extra_nfds=0, timeout_ms=1000, ret=0x0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1421
#4  0x00007fcdfe274aea in easy_transfer (multi=0x7fcde400fce0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:603
#5  0x00007fcdfe274d6f in easy_perform (data=0x7fcde400a8f0, events=false) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:696
#6  0x00007fcdfe274de1 in curl_easy_perform (data=0x7fcde400a8f0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:715
#7  0x00007fcdff4b06c2 in cpr::Session::makeRequest (this=0x7fcdf907ac00) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:215
#8  0x00007fcdff4b3128 in cpr::Session::Get (this=0x7fcdf907ac00) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:695
#9  0x0000000000945ae6 in cpr::Get<cpr::Url, cpr::SslOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, cpr::Parameters&, cpr::Timeout&> (ts=..., ts=..., ts=..., ts=..., ts=...) at /usr/local/include/cpr/api.h:60
#10 0x0000000000930789 in ConsulConnection::requestConsul (this=0x1fa8be0, mtd="GET", path="/v1/kv/appmesh/cluster", query=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
std::map with 3 elements, header=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
std::map with 0 elements, body=0x0, timeoutSec=60) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1065
#11 0x0000000000942e57 in ConsulConnection::blockWatchKv (this=0x1fa8be0, kvPath="/v1/kv/appmesh/cluster", lastIndex=9947, recurse=false) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1130
#12 0x0000000000942828 in ConsulConnection::watchScheduleThread (this=0x1fa8be0) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1201
#13 0x000000000094f9f7 in std::__invoke_impl<void, void (ConsulConnection::*&)(), ConsulConnection*&> (__f=@0x1fd7508: (void (ConsulConnection::*)(class ConsulConnection * const)) 0x9426a0 <ConsulConnection::watchScheduleThread()>, __t=@0x1fd7518: 0x1fa8be0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:73
#14 0x000000000094f922 in std::__invoke<void (ConsulConnection::*&)(), ConsulConnection*&> (__fn=@0x1fd7508: (void (ConsulConnection::*)(class ConsulConnection * const)) 0x9426a0 <ConsulConnection::watchScheduleThread()>, __args=@0x1fd7518: 0x1fa8be0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#15 0x000000000094f8e6 in std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x1fd7508, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:400
#16 0x000000000094f896 in std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>::operator()<, void>() (this=0x1fd7508) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:482
#17 0x000000000094f85d in std::__invoke_impl<void, std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>>(std::__invoke_other, std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>&&) (__f=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#18 0x000000000094f7ed in std::__invoke<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>>(std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>&&) (__fn=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#19 0x000000000094f7c5 in std::thread::_Invoker<std::tuple<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1fd7508) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
#20 0x000000000094f795 in std::thread::_Invoker<std::tuple<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()> > >::operator()() (this=0x1fd7508) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
#21 0x000000000094f56e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()> > > >::_M_run() (this=0x1fd7500) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
#22 0x00007fcdfe83bde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x00007fcdfe5de609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#24 0x00007fcdfe503133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fcdf987e700 (LWP 216815)):
#0  0x00007fcdfe4f699f in __GI___poll (fds=0x7fcdf987b8b0, nfds=2, timeout=1000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcdfe29de75 in Curl_poll (ufds=0x7fcdf987b8b0, nfds=2, timeout_ms=1000) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/select.c:374
#2  0x00007fcdfe29580f in multi_wait (multi=0x7fcde00117e0, extra_fds=0x0, extra_nfds=0, timeout_ms=1000, ret=0x0, extrawait=true, use_wakeup=true) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1282
#3  0x00007fcdfe295b18 in curl_multi_poll (multi=0x7fcde00117e0, extra_fds=0x0, extra_nfds=0, timeout_ms=1000, ret=0x0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1421
#4  0x00007fcdfe274aea in easy_transfer (multi=0x7fcde00117e0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:603
#5  0x00007fcdfe274d6f in easy_perform (data=0x7fcde0002ef0, events=false) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:696
#6  0x00007fcdfe274de1 in curl_easy_perform (data=0x7fcde0002ef0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:715
#7  0x00007fcdff4b06c2 in cpr::Session::makeRequest (this=0x7fcdf987bbd0) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:215
#8  0x00007fcdff4b3128 in cpr::Session::Get (this=0x7fcdf987bbd0) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:695
#9  0x0000000000945ae6 in cpr::Get<cpr::Url, cpr::SslOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, cpr::Parameters&, cpr::Timeout&> (ts=..., ts=..., ts=..., ts=..., ts=...) at /usr/local/include/cpr/api.h:60
#10 0x0000000000930789 in ConsulConnection::requestConsul (this=0x1fa8be0, mtd="GET", path="/v1/kv/appmesh/topology/appmesh-desktop", query=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
std::map with 3 elements, header=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
std::map with 0 elements, body=0x0, timeoutSec=60) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1065
#11 0x0000000000942e57 in ConsulConnection::blockWatchKv (this=0x1fa8be0, kvPath="/v1/kv/appmesh/topology/appmesh-desktop", lastIndex=1954, recurse=false) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1130
#12 0x00000000009424da in ConsulConnection::watchTopologyThread (this=0x1fa8be0) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1176
#13 0x000000000094f9f7 in std::__invoke_impl<void, void (ConsulConnection::*&)(), ConsulConnection*&> (__f=@0x1fd7478: (void (ConsulConnection::*)(class ConsulConnection * const)) 0x9422f0 <ConsulConnection::watchTopologyThread()>, __t=@0x1fd7488: 0x1fa8be0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:73
#14 0x000000000094f922 in std::__invoke<void (ConsulConnection::*&)(), ConsulConnection*&> (__fn=@0x1fd7478: (void (ConsulConnection::*)(class ConsulConnection * const)) 0x9422f0 <ConsulConnection::watchTopologyThread()>, __args=@0x1fd7488: 0x1fa8be0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#15 0x000000000094f8e6 in std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x1fd7478, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:400
#16 0x000000000094f896 in std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>::operator()<, void>() (this=0x1fd7478) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:482
#17 0x000000000094f85d in std::__invoke_impl<void, std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>>(std::__invoke_other, std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>&&) (__f=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#18 0x000000000094f7ed in std::__invoke<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>>(std::_Bind<void (ConsulConnection::*(ConsulConnection*))()>&&) (__fn=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#19 0x000000000094f7c5 in std::thread::_Invoker<std::tuple<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1fd7478) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
#20 0x000000000094f795 in std::thread::_Invoker<std::tuple<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()> > >::operator()() (this=0x1fd7478) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
#21 0x000000000094f56e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (ConsulConnection::*(ConsulConnection*))()> > > >::_M_run() (this=0x1fd7470) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
#22 0x00007fcdfe83bde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x00007fcdfe5de609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#24 0x00007fcdfe503133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fcdfa07f700 (LWP 216808)):
#0  0x00007fcdfe4f699f in __GI___poll (fds=0x7fcdfa07d010, nfds=2, timeout=1000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcdfe29de75 in Curl_poll (ufds=0x7fcdfa07d010, nfds=2, timeout_ms=1000) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/select.c:374
#2  0x00007fcdfe29580f in multi_wait (multi=0x7fcdec0205d0, extra_fds=0x0, extra_nfds=0, timeout_ms=1000, ret=0x0, extrawait=true, use_wakeup=true) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1282
#3  0x00007fcdfe295b18 in curl_multi_poll (multi=0x7fcdec0205d0, extra_fds=0x0, extra_nfds=0, timeout_ms=1000, ret=0x0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1421
#4  0x00007fcdfe274aea in easy_transfer (multi=0x7fcdec0205d0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:603
#5  0x00007fcdfe274d6f in easy_perform (data=0x7fcdec021330, events=false) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:696
#6  0x00007fcdfe274de1 in curl_easy_perform (data=0x7fcdec021330) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:715
#7  0x00007fcdff4b06c2 in cpr::Session::makeRequest (this=0x7fcdfa07d320) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:215
#8  0x00007fcdff4b3128 in cpr::Session::Get (this=0x7fcdfa07d320) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:695
#9  0x0000000000944300 in cpr::Get<cpr::Url, cpr::Timeout, cpr::SslOptions> (ts=..., ts=..., ts=...) at /usr/local/include/cpr/api.h:60
#10 0x00000000009375f7 in ConsulConnection::getHealthStatus (this=0x1fa8be0, hostName="appmesh-desktop", app="myapp") at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:251
#11 0x00000000009343c7 in ConsulConnection::viewCloudApps (this=0x1fa8be0) at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:184
#12 0x000000000085780a in RestHandler::apiCloudAppsView (this=0x1fad638, message=...) at /home/laoshanxi/new/app-mesh/src/daemon/rest/RestHandler.cpp:929
#13 0x000000000086a2bf in std::__invoke_impl<void, void (RestHandler::*&)(HttpRequest const&), RestHandler*&, HttpRequest const&> (__f=@0x7fcdec024750: (void (RestHandler::*)(class RestHandler * const, const class HttpRequest &)) 0x857770 <RestHandler::apiCloudAppsView(HttpRequest const&)>, __t=@0x7fcdec024760: 0x1fad638, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:73
#14 0x000000000086a1b7 in std::__invoke<void (RestHandler::*&)(HttpRequest const&), RestHandler*&, HttpRequest const&> (__fn=@0x7fcdec024750: (void (RestHandler::*)(class RestHandler * const, const class HttpRequest &)) 0x857770 <RestHandler::apiCloudAppsView(HttpRequest const&)>, __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#15 0x000000000086a161 in std::_Bind<void (RestHandler::*(RestHandler*, std::_Placeholder<1>))(HttpRequest const&)>::__call<void, HttpRequest const&, 0ul, 1ul>(std::tuple<HttpRequest const&>&&, std::_Index_tuple<0ul, 1ul>) (this=0x7fcdec024750, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:400
#16 0x000000000086a0bd in std::_Bind<void (RestHandler::*(RestHandler*, std::_Placeholder<1>))(HttpRequest const&)>::operator()<HttpRequest const&, void>(HttpRequest const&) (this=0x7fcdec024750, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:482
#17 0x0000000000869db2 in std::_Function_handler<void (HttpRequest const&), std::_Bind<void (RestHandler::*(RestHandler*, std::_Placeholder<1>))(HttpRequest const&)> >::_M_invoke(std::_Any_data const&, HttpRequest const&) (__functor=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#18 0x000000000080389b in std::function<void (HttpRequest const&)>::operator()(HttpRequest const&) const (this=0x7fcdfa07e520, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#19 0x0000000000800c19 in RestBase::handleRest(HttpRequest const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<void (HttpRequest const&)>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::function<void (HttpRequest const&)> > > > const&) (this=0x1fad638, message=..., restFunctions=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
std::map with 19 elements) at /home/laoshanxi/new/app-mesh/src/daemon/rest/RestBase.cpp:99
#20 0x00000000007f7575 in PrometheusRest::handleRest(HttpRequest const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<void (HttpRequest const&)>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::function<void (HttpRequest const&)> > > > const&) (this=0x1fad638, message=..., restFunctions=Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
std::map with 19 elements) at /home/laoshanxi/new/app-mesh/src/daemon/rest/PrometheusRest.cpp:88
#21 0x00000000007ffdf6 in RestBase::handle_get (this=0x1fad638, message=...) at /home/laoshanxi/new/app-mesh/src/daemon/rest/RestBase.cpp:29
#22 0x000000000086cfa3 in TcpHandler::handleTcpRest (this=0x7fcdec0012d0, message=...) at /home/laoshanxi/new/app-mesh/src/daemon/rest/TcpServer.cpp:103
#23 0x000000000086c9e8 in TcpHandler::handle_input (this=0x7fcdec0012d0) at /home/laoshanxi/new/app-mesh/src/daemon/rest/TcpServer.cpp:42
#24 0x00007fcdfecf395e in ACE_TP_Reactor::dispatch_socket_event(ACE_EH_Dispatch_Info&) () from /opt/appmesh/lib64/libACE-6.4.5.so
#25 0x00007fcdfecf3a38 in ACE_TP_Reactor::handle_socket_events(int&, ACE_TP_Token_Guard&) () from /opt/appmesh/lib64/libACE-6.4.5.so
#26 0x00007fcdfecf3d48 in ACE_TP_Reactor::dispatch_i(ACE_Time_Value*, ACE_TP_Token_Guard&) () from /opt/appmesh/lib64/libACE-6.4.5.so
#27 0x00007fcdfecf4028 in ACE_TP_Reactor::handle_events(ACE_Time_Value*) () from /opt/appmesh/lib64/libACE-6.4.5.so
#28 0x00007fcdfecd805c in ACE_Reactor::run_reactor_event_loop(int (*)(ACE_Reactor*)) () from /opt/appmesh/lib64/libACE-6.4.5.so
#29 0x0000000000999043 in TimerManager::runReactorEvent (reactor=0x1f3d680) at /home/laoshanxi/new/app-mesh/src/common/TimerHandler.cpp:111
#30 0x00000000007f27d2 in std::__invoke_impl<void, void (*&)(ACE_Reactor*), ACE_Reactor*&> (__f=@0x1f46498: 0x998f90 <TimerManager::runReactorEvent(ACE_Reactor*)>, __args=@0x1f464a0: 0x1f3d680) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#31 0x00000000007f2742 in std::__invoke<void (*&)(ACE_Reactor*), ACE_Reactor*&> (__fn=@0x1f46498: 0x998f90 <TimerManager::runReactorEvent(ACE_Reactor*)>, __args=@0x1f464a0: 0x1f3d680) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#32 0x00000000007f26f6 in std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x1f46498, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:400
#33 0x00000000007f26a6 in std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)>::operator()<, void>() (this=0x1f46498) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/functional:482
#34 0x00000000007f266d in std::__invoke_impl<void, std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)>>(std::__invoke_other, std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)>&&) (__f=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#35 0x00000000007f25fd in std::__invoke<std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)>>(std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)>&&) (__fn=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#36 0x00000000007f25d5 in std::thread::_Invoker<std::tuple<std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1f46498) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
#37 0x00000000007f25a5 in std::thread::_Invoker<std::tuple<std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)> > >::operator()() (this=0x1f46498) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
#38 0x00000000007f237e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (*(ACE_Reactor*))(ACE_Reactor*)> > > >::_M_run() (this=0x1f46490) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
#39 0x00007fcdfe83bde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#40 0x00007fcdfe5de609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#41 0x00007fcdfe503133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

## Description
Is multi-thread REST call supported?

## Expected Behavior
should work for C++ multi-thread

## Actual Behavior
From symptom seems some lock was there to block myulti-thread

## Possible Fix
N/A

## Steps to Reproduce
So far not, still under integration and testing

## Context
[App Mesh](https://github.com/laoshanxi/app-mesh)

## Your Environment

* Version used: cpr 1.9.2
* Where did you get it from (e.g. conan, vcpkg, master, ...): github release
* Operating System and version:Ubuntu 20.04
* Link to a small example:

**Comment by laoshanxi** [comment]
sorry, not cpr issue, some lock in server side. close
