### ISSUE TITLE
[question] some cpr::Get() will create new thread, some will not, how to avoid new thread create for GET

### ISSUE THREAD

**Issue by laoshanxi** [libcpr/cpr#834]
Hi,

I used multiple cpr::Get() but the first case will create new thread, the second case will not, is there something wrong? how can I avoid new thread create for GET call.

- Case 1 will create new thread

https://github.com/laoshanxi/app-mesh/blob/main/src/daemon/consul/ConsulConnection.cpp#L251
`auto resp = cpr::Get(cpr::Url{url, restPath},cpr::Timeout{1000 * 10},cpr::Ssl(cpr::ssl::VerifyHost{false}, cpr::ssl::VerifyPeer{false}));`
```
#0  __pthread_create_2_1 (newthread=0x7fcdec0237f0, attr=0x0, start_routine=0x7fcdfe270f84 <curl_thread_create_thunk>, arg=0x7fcdec023810)
    at pthread_create.c:625
#1  0x00007fcdfe27105c in Curl_thread_create (func=0x7fcdfe2637cd <getaddrinfo_thread>, arg=0x7fcdec029288)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/curl_threads.c:72
#2  0x00007fcdfe263b99 in init_resolve_thread (data=0x7fcdec018f70, hostname=0x7fcdec025890 "appmesh-desktop", port=6060, hints=0x7fcdfa07ccb0)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/asyn-thread.c:463
#3  0x00007fcdfe2640ee in Curl_resolver_getaddrinfo (data=0x7fcdec018f70, hostname=0x7fcdec025890 "appmesh-desktop", port=6060, waitp=0x7fcdfa07cd64)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/asyn-thread.c:715
#4  0x00007fcdfe27b71a in Curl_getaddrinfo (data=0x7fcdec018f70, hostname=0x7fcdec025890 "appmesh-desktop", port=6060, waitp=0x7fcdfa07cd64)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/hostasyn.c:122
#5  0x00007fcdfe27cdb8 in Curl_resolv (data=0x7fcdec018f70, hostname=0x7fcdec025890 "appmesh-desktop", port=6060, allowDOH=true, entry=0x7fcdfa07ce40)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/hostip.c:721
#6  0x00007fcdfe27cf10 in Curl_resolv_timeout (data=0x7fcdec018f70, hostname=0x7fcdec025890 "appmesh-desktop", port=6060, entry=0x7fcdfa07ce40,
    timeoutms=10000) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/hostip.c:896
#7  0x00007fcdfe2b8a9f in resolve_server (data=0x7fcdec018f70, conn=0x7fcdec001710, async=0x7fcdfa07cf84)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/url.c:3402
#8  0x00007fcdfe2ba03d in create_conn (data=0x7fcdec018f70, in_connect=0x7fcdfa07cf40, async=0x7fcdfa07cf84)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/url.c:4031
#9  0x00007fcdfe2ba32d in Curl_connect (data=0x7fcdec018f70, asyncp=0x7fcdfa07cf84, protocol_done=0x7fcdfa07cf85)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/url.c:4121
#10 0x00007fcdfe2964ee in multi_runsingle (multi=0x7fcdec0200a0, nowp=0x7fcdfa07d030, data=0x7fcdec018f70)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:1814
#11 0x00007fcdfe297b05 in curl_multi_perform (multi=0x7fcdec0200a0, running_handles=0x7fcdfa07d120)
    at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/multi.c:2590
#12 0x00007fcdfe274b06 in easy_transfer (multi=0x7fcdec0200a0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:606
#13 0x00007fcdfe274d6f in easy_perform (data=0x7fcdec018f70, events=false) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:696
#14 0x00007fcdfe274de1 in curl_easy_perform (data=0x7fcdec018f70) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:715
#15 0x00007fcdff4b06c2 in cpr::Session::makeRequest (this=0x7fcdfa07d320) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:215
#16 0x00007fcdff4b3128 in cpr::Session::Get (this=0x7fcdfa07d320) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:695
#17 0x0000000000944300 in cpr::Get<cpr::Url, cpr::Timeout, cpr::SslOptions> (ts=..., ts=..., ts=...) at /usr/local/include/cpr/api.h:60
#18 0x00000000009375f7 in ConsulConnection::getHealthStatus (this=0x1fa8be0, hostName="appmesh-desktop", app="myapp")
    at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:251
```

- Case 2 will not create new thread

https://github.com/laoshanxi/app-mesh/blob/main/src/daemon/consul/ConsulConnection.cpp#L1065
`*response = cpr::Post(cpr::Url{restURL, path}, sslOpts, cprHeader, cprParam, cprBody, cprTimeout);`
```
(gdb) bt
#0  easy_perform (
    data=0x8d54f9 <__gnu_cxx::operator==<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >(__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+41>, events=205) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:649
#1  0x00007fcdfe274de1 in curl_easy_perform (data=0x7fcde0002ef0) at /home/laoshanxi/app-mesh/build/cpr/build/_deps/curl-src/lib/easy.c:715
#2  0x00007fcdff4b06c2 in cpr::Session::makeRequest (this=0x7fcdf987bbd0) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:215
#3  0x00007fcdff4b3128 in cpr::Session::Get (this=0x7fcdf987bbd0) at /home/laoshanxi/app-mesh/build/cpr/cpr/session.cpp:695
#4  0x0000000000945ae6 in cpr::Get<cpr::Url, cpr::SslOptions&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, cpr::Parameters&, cpr::Timeout&> (ts=..., ts=..., ts=..., ts=..., ts=...) at /usr/local/include/cpr/api.h:60
#5  0x0000000000930789 in ConsulConnection::requestConsul (this=0x1fa8be0, mtd="GET", path="/v1/kv/appmesh/topology/appmesh-desktop", Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':

    query=std::map with 3 elements, Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
header=std::map with 0 elements, body=0x0, timeoutSec=60)
    at /home/laoshanxi/new/app-mesh/src/daemon/consul/ConsulConnection.cpp:1065

```

Regards

**Comment by COM8** [comment]
We do not create any new threads inside cpr. This is something you might want to ask the curl maintainers: https://github.com/curl/curl

We only wrap curl.
In case you get a reply, feel free to let us know so we can implement the required changes/options.

**Comment by laoshanxi** [comment]
I found that's because curl need resolve hostname (https://everything.curl.dev/libcurl/names), but its wired since the hostname is local hostname, and the resolve failed.  tried curl with local hostname have no issue.

**Comment by laoshanxi** [comment]
every time when I use hostname to call REST, new thread will be created for name resolve, I believe there could have cache for long running daemon application instead of resolve same hostname very time to spawn a  thread.
