### ISSUE TITLE
AddressSanitizer:DEADLYSIGNAL - while performing simple GET request

### ISSUE THREAD

**Issue by JoSoReal** [libcpr/cpr#940]
### Description

I'm using the AddressSanitizer during the Debug build and it throws an error while performing the example GET request from your documentation. It also fails for every GET request I'm performing. The error is shown below. I added my simple Test program in the reproduction section.

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7760==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000c (pc 0x00127254 bp 0x7eeb8eec sp 0x7eeb8ec8 T0)
==7760==The signal is caused by a READ memory access.
==7760==Hint: address points to the zero page.
    #0 0x127253 in std::deque<std::shared_ptr<cpr::Interceptor>, std::allocator<std::shared_ptr<cpr::Interceptor> > >::_M_destroy_data_aux(std::_Deque_iterator<std::shared_ptr<cpr::Interceptor>, std::shared_ptr<cpr::Interceptor>&, std::shared_ptr<cpr::Interceptor>*>, std::_Deque_iterator<std::shared_ptr<cpr::Interceptor>, std::shared_ptr<cpr::Interceptor>&, std::shared_ptr<cpr::Interceptor>*>) /usr/include/c++/8/bits/deque.tcc:851
    #1 0x12581f in std::deque<std::shared_ptr<cpr::Interceptor>, std::allocator<std::shared_ptr<cpr::Interceptor> > >::_M_destroy_data(std::_Deque_iterator<std::shared_ptr<cpr::Interceptor>, std::shared_ptr<cpr::Interceptor>&, std::shared_ptr<cpr::Interceptor>*>, std::_Deque_iterator<std::shared_ptr<cpr::Interceptor>, std::shared_ptr<cpr::Interceptor>&, std::shared_ptr<cpr::Interceptor>*>, std::allocator<std::shared_ptr<cpr::Interceptor> > const&) /usr/include/c++/8/bits/stl_deque.h:2082
    #2 0x1240c7 in std::deque<std::shared_ptr<cpr::Interceptor>, std::allocator<std::shared_ptr<cpr::Interceptor> > >::~deque() /usr/include/c++/8/bits/stl_deque.h:1055
    #3 0x122767 in std::queue<std::shared_ptr<cpr::Interceptor>, std::deque<std::shared_ptr<cpr::Interceptor>, std::allocator<std::shared_ptr<cpr::Interceptor> > > >::~queue() /usr/include/c++/8/bits/stl_queue.h:96
    #4 0x122797 in cpr::Session::~Session() libs/include/cpr/session.h:51
    #5 0x122a23 in cpr::Response cpr::Get<cpr::Url, cpr::Authentication, cpr::Parameters>(cpr::Url&&, cpr::Authentication&&, cpr::Parameters&&) libs/include/cpr/api.h:58
    #6 0x11f8ab in main main.cpp:26
    #7 0x76abb717 in __libc_start_main /home/pi/dev/glibc-buster/csu/libc-start.c:308

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/8/bits/deque.tcc:851 in std::deque<std::shared_ptr<cpr::Interceptor>, std::allocator<std::shared_ptr<cpr::Interceptor> > >::_M_destroy_data_aux(std::_Deque_iterator<std::shared_ptr<cpr::Interceptor>, std::shared_ptr<cpr::Interceptor>&, std::shared_ptr<cpr::Interceptor>*>, std::_Deque_iterator<std::shared_ptr<cpr::Interceptor>, std::shared_ptr<cpr::Interceptor>&, std::shared_ptr<cpr::Interceptor>*>)
==7760==ABORTING
```

### Example/How to Reproduce

Run the following program with AddressSanitizer enabled. Set compiler options: "-fsanitize=address -static-libasan"

```
#include <cstdlib>
#include <iostream>
#include <cpr/cpr.h>

using namespace std;

int main(int argc, char** argv) {
    std::cout << "Hello World!";
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/libcpr/cpr/contributors"},
                      cpr::Authentication{"user", "pass", cpr::AuthMode::BASIC},
                      cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    return 0;
}
```

### Possible Fix

There's an issue with the Session class destructor. Probably it's a solution to have a proper destructor instead of the default one.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

CPR lib version: 1.9.6
Operating system: Debian

**Comment by COM8** [comment]
Thanks for reporting! I will look into it.

**Comment by COM8** [comment]
Can not reproduce it. This is my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.20)
project(cpr_example)

set(CMAKE_CXX_STANDARD 17)

# Set to C++ 11 if you are using cpr <= 1.9.x
# More: https://github.com/libcpr/cpr#supported-releases
# set(CMAKE_CXX_STANDARD 11)

# Address sanitizer
include(CheckCXXCompilerFlag)
include(CheckCXXSourceRuns)
set(ADDR_SAN_FLAGS "-fsanitize=address")
set(PREV_FLAG ${CMAKE_REQUIRED_FLAGS})
set(CMAKE_REQUIRED_FLAGS "${ADDR_SAN_FLAGS}")
check_cxx_source_runs("int main() { return 0; }" ADDRESS_SANITIZER_AVAILABLE)
set(CMAKE_REQUIRED_FLAGS ${PREV_FLAG})
if(ADDRESS_SANITIZER_AVAILABLE)
    set(ALL_SAN_FLAGS "${ALL_SAN_FLAGS} ${ADDR_SAN_FLAGS}")
else()
  message(FATAL_ERROR "Address sanitizer not supported.")
endif()
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${ADDR_SAN_FLAGS} -fno-omit-frame-pointer -fno-optimize-sibling-calls" CACHE INTERNAL "Flags used by the C compiler during address sanitizer builds." FORCE)
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${ADDR_SAN_FLAGS} -fno-omit-frame-pointer -fno-optimize-sibling-calls" CACHE INTERNAL "Flags used by the C++ compiler during address sanitizer builds." FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG}" CACHE INTERNAL "Flags used for the linker during address sanitizer builds" FORCE)

# Set a default build type if none was specified
# Based on: https://github.com/openchemistry/tomviz/blob/master/cmake/BuildType.cmake
set(DEFAULT_BUILD_TYPE "Release")
if(EXISTS "${CMAKE_SOURCE_DIR}/.git")
  set(DEFAULT_BUILD_TYPE "Debug")
endif()
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  message(STATUS "Setting build type to '${DEFAULT_BUILD_TYPE}' as none was specified.")
  set(CMAKE_BUILD_TYPE "${DEFAULT_BUILD_TYPE}" CACHE STRING "Choose the type of build." FORCE)
  # Set the possible values of build type for cmake-gui
  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
endif()

add_executable(cpr_example main.cpp)

if(WIN32) # Install dlls in the same directory as the executable on Windows
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
endif()

include(FetchContent)
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/libcpr/cpr.git
                         GIT_TAG 340acc5cdad624b9398827eec2832fe2fd05f966) # The commit hash for 1.9.6. Replace with the latest from: https://github.com/libcpr/cpr/releases
FetchContent_MakeAvailable(cpr)

target_link_libraries(cpr_example PRIVATE cpr::cpr)

```

Could you please provide a complete minimal example project?

**Comment by COM8** [comment]
Closing for no response.
