### ISSUE TITLE
..

### ISSUE THREAD

**Issue by mrmednmn** [libcpr/cpr#967]

**Comment by COM8** [comment]
What error message/code do you get?

**Comment by mrmednmn** [comment]
> What error message/code do you get?

just the app keep stpping , there is no error with the build

**Comment by COM8** [comment]
I need some kind of error message, else I can not really help you, sorry. I also never have been working with android before.

Based on your description I'd say this is something related to it not finding a library.

**Comment by mrmednmn** [comment]
> I need some kind of error message, else I can not really help you, sorry. I also never have been working with android before.
> 
> Based on your description I'd say this is something related to it not finding a library.

**### When i try with curl i get this error:**
test E FATAL EXCEPTION: main
Process: test.market.ctest, PID: 17421
java.lang.UnsatisfiedLinkError: dlopen failed: library "libssl.so.3" not found: needed by /data/app/~~Acr3ipqUKBqIViSYWuPSEw==/test.market.ctest-C6mjD7BGvZ7qpxKkqlaDDA==/base.apk!/lib/x86_64/libctest.so in namespace clns-6
at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
at java.lang.System.loadLibrary(System.java:1661)
at test.market.ctest.MainActivity.<clinit>(MainActivity.java:14)
at java.lang.Class.newInstance(Native Method)
at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
at android.app.Instrumentation.newActivity(Instrumentation.java:1378)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
2023-09-30 09:58:14.616 17421-17447 libEGL test.market.ctest D loaded /vendor/lib64/egl/libGLESv2_emulation.so
2023-09-30 09:58:14.703 17421-17421 Process test.market.ctest I Sending signal. PID: 17421 SIG: 9
2023-09-30 10:02:39.839 17521-17521 Compatibil...geReporter test.market.ctest D Compat change id reported: 171979766; UID 10191; state: ENABLED
2023-09-30 10:02:39.849 17521-17521 Compatibil...geReporter test.market.ctest D Compat change id reported: 242716250; UID 10191; state: DISABLED
2023-09-30 10:02:40.596 17521-17521 ziparchive test.market.ctest W Unable to open '/data/app/~~qN2GID3WnqiWbiYrrhXFaw==/test.market.ctest-04fXAJiP3TDZHw9TAfj44Q==/base.dm': No such file or directory
2023-09-30 10:02:40.596 17521-17521 ziparchive test.market.ctest W Unable to open '/data/app/~~qN2GID3WnqiWbiYrrhXFaw==/test.market.ctest-04fXAJiP3TDZHw9TAfj44Q==/base.dm': No such file or directory
2023-09-30 10:02:41.609 17521-17521 nativeloader test.market.ctest D Configuring clns-6 for other apk /data/app/~~qN2GID3WnqiWbiYrrhXFaw==/test.market.ctest-04fXAJiP3TDZHw9TAfj44Q==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~qN2GID3WnqiWbiYrrhXFaw==/test.market.ctest-04fXAJiP3TDZHw9TAfj44Q==/lib/x86_64:/data/app/~~qN2GID3WnqiWbiYrrhXFaw==/test.market.ctest-04fXAJiP3TDZHw9TAfj44Q==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/test.market.ctest
2023-09-30 10:02:41.719 17521-17521 GraphicsEnvironment test.market.ctest V Currently set values for:
2023-09-30 10:02:41.720 17521-17521 GraphicsEnvironment test.market.ctest V angle_gl_driver_selection_pkgs=[]
2023-09-30 10:02:41.727 17521-17521 GraphicsEnvironment test.market.ctest V angle_gl_driver_selection_values=[]
2023-09-30 10:02:41.823 17521-17521 GraphicsEnvironment test.market.ctest V ANGLE GameManagerService for test.market.ctest: false
2023-09-30 10:02:41.836 17521-17521 GraphicsEnvironment test.market.ctest V test.market.ctest is not listed in per-application setting
2023-09-30 10:02:41.847 17521-17521 GraphicsEnvironment test.market.ctest V Neither updatable production driver nor prerelease driver is supported.
2023-09-30 10:02:42.339 17521-17521 AndroidRuntime test.market.ctest D Shutting down VM
2023-09-30 10:02:42.372 17521-17521 AndroidRuntime test.market.ctest E FATAL EXCEPTION: main
Process: test.market.ctest, PID: 17521
java.lang.UnsatisfiedLinkError: dlopen failed: library

**Comment by COM8** [comment]
That's your error:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libssl.so.3" not found:
```
Your app can not find `libssl.so.3`. You need to tell your app how and where to find it.

**Comment by mrmednmn** [comment]
> to

I add it its not solve the problem

**Comment by mrmednmn** [comment]
..
